/**
 * API Tienda Virtual
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemPedido } from './itemPedido';


export interface Pedido { 
    clienteEmail: string;
    fecha?: string;
    items: Array<ItemPedido>;
}

