/**
 * API Tienda Virtual
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Producto { 
    id?: number;
    nombre?: string;
    precio?: number;
    categoria?: string;
    stock?: number;
}

